### ISSUE TITLE
Issue while running simulation

### ISSUE THREAD

**Issue by rajatserc** [It4innovations/Maui-Simulation#5]
Hello Georg,
I have modified the resource trace and workload files, along with the control_example.sh, for our setup. I have updated the maui.cfg to reflect our queue configuration.
However, I get the following error when I run the simulation:
----------------------------------------------------------------------
ERROR:    'checknode' failed
ERROR:  cannot locate node 'sahasrat_95'

ERROR:    'setres' failed
ERROR:    no matches found for node expression
ERROR:    cannot determine nodelist for '^sahasrat_95$'

scheduling will stop in 00:14:15 at iteration 2620

ERROR:    cannot locate reservation '^sahasrat_95$.0'
----------------------------------------------------------------------
Here, sahasrat_95 is the NID, and I have update the resource trace with 1376 nodes. But, the simulation give the above error and records 1008 nodes only.

Could you please help setup this up correctly?
Thanks in advance.

Regards,
Rajat

**Comment by gzitzlsb-it4i** [comment]
Hello,

If it sees 1008 nodes, it looks to me that our original Resource.Trace1 file was used. Once you created your own one (with a different name), make sure to reference it properly in maui.cfg (SIMRESOURCETRACEFILE).

If that was not it, could you please share the trace files, maui.cfg and the modified control_example.sh? It's hard to find the error w/o it.

Best regards,

Georg

**Comment by rajatserc** [comment]
Hello Georg,
Thank you for the quick response.
I am attaching the mentioned files.

[Workload.Trace_example.txt](https://github.com/It4innovations/Maui-Simulation/files/5865270/Workload.Trace_example.txt)
[maui.cfg.txt](https://github.com/It4innovations/Maui-Simulation/files/5865272/maui.cfg.txt)
[Resource.Trace1.txt](https://github.com/It4innovations/Maui-Simulation/files/5865273/Resource.Trace1.txt)

**Comment by gzitzlsb-it4i** [comment]
Hello,

I think I know what's the problem. I assume the original maui.cfg is still used. Please check:
$ ls -hal /usr/local/maui/maui.cfg 
lrwxrwxrwx 1 root staff 28 Jan 25 09:37 /usr/local/maui/maui.cfg -> /home/userx/workdir/maui.cfg

As you can see, it links to maui.cfg originally provided (if userx was not changed). You can replace the maui.cfg wherever the link is pointing to. Then, it will use the right maui.cfg.
Also check with the following command to see your own nodes:
$ showstats -n

Best regards,

Georg

**Comment by rajatserc** [comment]
Hello Georg,
I did check the link and it is pointing to the correct file. I provided the correct config file using --configfile as well. 

And with "showstats -n" it shows the names of the nodes specified in my resource trace, but selects only 1008 nodes.
Summary:  1008 131072MB Nodes  100.00% Avail    0.00% Busy  (Current: 100.00% Avail    0.00% Busy)

System Summary:  1008 Nodes  100.00% Avail    0.00% Busy  (Current: 100.00% Avail    0.00% Busy)

**Comment by gzitzlsb-it4i** [comment]
Hello,

the reason that you only see 1008 nodes is that the nodes you added to the resource trace file have invalid columns (compare columns of line 1008 vs. 1009 et. seqq.).
Could you please confirm that this is the problem?

Best regards,

Georg

**Comment by rajatserc** [comment]
Hello Georg,
You are right! My apologies. I had made the necessary changes but loaded a different file by mistake. Now it shows the correct amount of resources.

Could you also suggest some changes for the control_example.sh script? As it seems that I am not advancing the time steps correctly.

**Comment by gzitzlsb-it4i** [comment]
Hello,

good to know that it's solved now.

We created the control script automatically from our historic data.
The idea is the following:
The first job for us had the timestamp 1486539500, which is used as the reference starting point for the simulation. So, you need to replace this time step with the one of your first job.
Second, the simulation is advanced by this:
$ schedctl --host=$HOST --port=$PORT -s $((2449-$off))I # 1486551471
This advances by (2449-$off) seconds plus does some compensation with $off because the simulation always advances in step length of the resolution for the simulation (here, 5 seconds). In the end, after this command we'll be at timestamp 1486551471.
We advance from one event to the next, where each event is a node reservation (downtime or node(s) coming back from downtime).

For simplicity you can remove the reservations and not simulating node/system downtime and just advance as much as you want.

Best regards,

Georg
